---
port: 4000
host: 0.0.0.0
safe: false

exclude: [README.md, .gitignore]
timezone: null
lsi: false
markdown: kramdown

### content configuration ###
title:       "Automatic Summarization for Creative Writing "
keywords:    "workshop, creative writing, automatic summarization"
description: "The official website for the Workshop on Automatic Summarization for Creative Writing "
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"

collections:
  - pages_2022

theme: jekyll-theme-cayman